# Состояния потока, прерывание
## Состояния потока
| Название | Оригинал | Описание                                                                                                                                                                                                                                                                                                                     |
| --- | --- |------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Переходное | new | Поток находится в этом состоянии очень недолго, только во время создания.<br/>Он получает все необходимые ресурсы и выполняе инициализацию.<br/>На этой стадии он получает право на выделение процессорного времени.<br/>Далее поток переводится планировщиком в активное или заблокированное состояние                      |
| Активное | runnable | В таком состоянии поток будет выполняться тогда, когда у механизма разделения времени процессора появятся для него свободные кванты.<br/>Таким образом, поток может как не выполняться, так и выполняться, однако ничто не препятствует последнему при получении потоком прцоессорного времени (он не мертв и не блокирован) |
| Блокировки | blocked | Поток может выполняться, однако есть что-то, что мешает ему это сделать.<br/>Пока поток имеет данный статус, квантирующий время процессор пропускает его очередь и не выделяет ему циклов на выполнение до тех пор, пока поток не перейдет в рабочее состояние                                                               |
| Завершенное | dead | В этом состоянии поток не ставится на выполнение и не получает процессорного времени.<br/>Его задача завершена, и он не может стать активным.<br/>Одним из способов перехода в завершенное состояние является возврат из метода `run()`, но поток задачи также может быть прерван                                            |

_Эккель Б. Философия Java. 4-е полное изд. Стр. 946_

## Переход в состояние blocked
Поток может перейти в блокированное состояние по следующим причинам:
* использован метод `sleep()` - после этого поток будет бездействовать заданное время
* использован метод `wait()` - поток будет простаиватьдо тех пор, пока не получит сообщение о возобновлении работы: `notify()` или `notifyAll()` (эквивалентно `signal()` и `signalAll()` из Java SE5)
* поток ожидает ввода/вывода
* поток пытается вызвать синхронизированный метод другого потока, но его объект блокировки недоступен

_Эккель Б. Философия Java. 4-е полное изд. Стр. 947_

## Идея прерывания
Выход из `Runnable.run()` на середине сложнее,чем ожидание до проверки флага отмены.При выходе из заблокированно задачи может возникнуть необходимость в освобождении ресурсов. По этой причине выход из середины метода `run()` задачи больше напоминает исключение, чем что-либо еще. По этой причине, в потоках Java для такой отмены применяются исключения.<br/>
При этом, исключеня никогда не доставляются асинхронно. Таким образом, не сущевствует опасности прерывания на середине команды/вызова метода.<br/>
Чтобы вернуться в заведомо допустимое состояние при завершении задачи, необходимо тщательно написать `catch` для освобождения всех ресурсов.<br/>
_Эккель Б. Философия Java. 4-е полное изд. Стр. 947_

## Вызов `interrupt` и `Executor`: shutdownNow, cancel
Чтобы вызыывать  `interrupt()`, необходимо иметь ссылку на объект `Thread`.<br/>
[Пример](examples/java/threads/interruption/Launcher.java)
```java
class SomeTask implements Runnable {

    @Override
    public void run() {
        try {
            TimeUnit.MILLISECONDS.sleep(100);
        } catch (InterruptedException e) {
            System.err.println("Was interrupted: " + e.getMessage());
        }
    }
}
```
```java
private static void interruptViaThreadInterrupt() {
    Thread thread = new Thread(new SomeTask());
    thread.start();
    thread.interrupt();
}
```
Вывод:
```
Was interrupted: sleep interrupted
```
Новая библиотека `concurrent` старается избегать прямых манипуляций с объектами `Thread` и вместо этого пытается все делать через `Executor`.<br/>
Если вызывать для объектов `Executor` метод `shutdownNow()` (**Не** `shutdown`), он отправит вызов `interrupt()` каждому из свох запущенных им потоков. Это разумно, потому что, обычно, требуется закрыть все задачи конкретного объекта `Executor` при завершении части программы.<br/>
[Пример](examples/java/threads/interruption/Launcher.java)
```java
private static void interruptViaExecutorShutDownNow() {
    ExecutorService executorService = Executors.newCachedThreadPool();
    IntStream.range(0, 2).forEach(index -> executorService.execute(new SomeTask()));
    executorService.shutdownNow();
}
```
Вывод
```
Was interrupted: sleep interrupted
Was interrupted: sleep interrupted
```
Если требуется закрыть только одну задачу у `Executor`, можно  получить ссылку на контекст задачи при ее запуске - для этого вместо `execute()` вызывается метод `submit()`, который возвращает `Future<?>`. На `Future` можно вызывать метод `cancel()` и таким образом прервать задачу. Если передать `true` в вызов, осуществляется разрешение вызова `interrupt()` для этого потока с целью его остановки<br/>
Однако, если задача уже начала выполняться, `Future.cancel()` ее не остановит
```java
private static void interruptViaFutureCancel() throws InterruptedException {
    ExecutorService executorService = Executors.newCachedThreadPool();
    Future<?> future = executorService.submit(new SomeTask());
    future.cancel(true);
}
```
Вывод
```
```
_Эккель Б. Философия Java. 4-е полное изд. Стр. 948_<br/>
https://habr.com/ru/post/133413/

## Не все можно прервать
Вызов `sleep` (или другого метода, требующего перехвата `InterruptedException`) можно прервать. Однако, если задача пытается установить синхронизировнную блокировку или выполнить ввод/вывод, ее прервать не удастся<br/>
[Пример](examples/java/threads/interruption/WaitingForSynchronizedBlockTask.java)
```java
class WaitingForSynchronizedBlockTask implements Runnable {
    public WaitingForSynchronizedBlockTask() {
        System.out.println("Блокируем синхронизированный блок");
        new Thread(this::syncBlock).start();
    }

    @Override
    public void run() {
        System.out.println("Пытаемся войти в синхронизированный блок");
        syncBlock();
        System.out.println("Синхронизированный блок выполнен");
    }

    private synchronized void syncBlock() {
        while(true) {
            Thread.yield();
        }
    }
}
```
```java
private static void interruptRunnableWaitingForSync() throws InterruptedException {
    interruptWithExitOnCoolDown(new WaitingForSynchronizedBlockTask());
}

private static void interruptWithExitOnCoolDown(Runnable runnable) throws InterruptedException {
    ExecutorService executorService = Executors.newCachedThreadPool();
    executorService.execute(runnable);
    executorService.shutdownNow();
    TimeUnit.SECONDS.sleep(3);
    System.out.println("Вырубаем приложение, так как задача не может завершиться");
    System.exit(0);
}
```
Вывод
```
Блокируем синхронизированный блок
Пытаемся войти в синхронизированный блок
Вырубаем приложение, так как задача не может завершиться
```
[Пример](examples/java/threads/interruption/WaitingForIoTask.java)
```java
public class WaitingForIoTask implements Runnable {
    @Override
    public void run() {
        System.out.println("Ожидание ввода");
        try (InputStreamReader inputStreamReader = new InputStreamReader(System.in);
             BufferedReader bufferedReader = new BufferedReader(inputStreamReader)) {
            String currentLine;
            while ((currentLine = bufferedReader.readLine()) != null && currentLine.length() != 0) {
                System.out.println(currentLine);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```
```java
private static void interruptRunnableWaitingForIO() throws InterruptedException {
    interruptWithExitOnCoolDown(new WaitingForIoTask());
}
```
Вывод
```
Ожидание ввода
Вырубаем приложение, так как задача не может завершиться
```
_Эккель Б. Философия Java. 4-е полное изд. Стр. 950_

## Каналы nio предоставляют удобный механизм прерывания ввода/вывода
Блокированный `nio`-каналы автоматически реагируют на прерывание
```java
class TaskWithNio implements Runnable {
    private final SocketChannel channel;

    public TaskWithNio(SocketChannel channel) {
        this.channel = channel;
    }

    @Override
    public void run() {
        System.out.println("Начало чтения из канала");
        try {
            channel.read(ByteBuffer.allocate(1));
        } catch(ClosedByInterruptException cbie) {
            System.err.println("ClosedByInterruptException " + cbie.getMessage());
        } catch (AsynchronousCloseException ace) {
            System.err.println("AsynchronousCloseException " + ace.getMessage());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```
```java
private static void interruptChannel() throws IOException, InterruptedException {
    ExecutorService executorService = Executors.newCachedThreadPool();
    executorService.execute(new TaskWithNio(prepareSocketChannel()));
    TimeUnit.SECONDS.sleep(1);
    executorService.shutdownNow();
}

private static SocketChannel prepareSocketChannel() throws IOException {
    ServerSocket socket = new ServerSocket(8082);
    InetSocketAddress address = new InetSocketAddress("localhost", 8082);
    return SocketChannel.open(address);
}
```
Вывод
```
Начало чтения из канала
ClosedByInterruptException null
```
```java
private static void closeChannel() throws IOException, InterruptedException {
    ExecutorService executorService = Executors.newCachedThreadPool();
    SocketChannel channel = prepareSocketChannel();
    executorService.execute(new TaskWithNio(channel));
    TimeUnit.SECONDS.sleep(1);
    channel.close();
}
```
Вывод
```
Начало чтения из канала
AsynchronousCloseException null
```
_Эккель Б. Философия Java. 4-е полное изд. Стр. 951_

## Прерывание задач, заблокированных по `ReentrantLock`
Ситуация, в которой задача может быть заблокирована без возможности прерывания (IO, ожидание synchronized), может парализовать работу программы.<br/>
В Java SE5 `cuncurrency` появилась возможность прерывания задач, заблокированных по `ReentrantLock` (в отличии от задач, заблокированных по `synchronized`)<br/>
[Пример](examples/java/threads/interruption/TaskWithReetrantLock.java)
```java
public class TaskWithReetrantLock implements Runnable {
    private final Lock lock;

    public TaskWithReetrantLock() {
        lock = new ReentrantLock();
        lock.lock();
    }

    @Override
    public void run() {
        System.out.println("waiting for operation");
        operation();
        System.out.println("Broken out of blocked call");
    }

    private void operation() {
        try {
            lock.lockInterruptibly();
            System.out.println("Lock accured in operation");
        } catch (InterruptedException e) {
            System.out.println("Interrupted in operation: " + e);
        }
    }
}
```
```java
private static void interruptLock() throws InterruptedException {
    ExecutorService executorService = Executors.newCachedThreadPool();
    executorService.execute(new TaskWithReetrantLock());
    TimeUnit.SECONDS.sleep(1);
    executorService.shutdownNow();
}
```
Вывод
```
waiting for operation
Interrupted in operation: java.lang.InterruptedException
Broken out of blocked call
```
_Эккель Б. Философия Java. 4-е полное изд. Стр. 953_

## Когда случается прерывание и проверка состояния прерывания
При вызове `interrupt()` для потока прерывание может случится только при входе в блокирующую операцию или если задача уже находится там (кроме непрерываемого ввода/вывода и synchronized).<br/>
Есть возможность проверки _состояния прерывания_ путем вызова метода `interrupted()`<br/>
Помимо того, что `interrupted()` сообщает, был ли вызван `interrupt()`, он еще и сбрасывает состояние прерывания. Это позволяет предотвратить повторное оповещение о прерывании.
```java

```
_Эккель Б. Философия Java. 4-е полное изд. Стр. 954-955_