# CompletableFuture
## Краткое описание `CompletableFuture`
Класс `CompletableFuture` реализует интерфейсы `Future` и `CompletionStage` (содержащий методы на разные случаи жизни).<br/>
Главное преимущество, `CompletableFuture` в том, что он позволяет координировать действия без написания вложенных обтаных вызовов<br/>
_Коузен К. Современный Java: Рецепты программирования. Стр. 206_

## Завершение `CompletableFuture`
| Метод | Комментарий                                                                                           |
| --- |-------------------------------------------------------------------------------------------------------|
| `public boolean complete(T value)` | Используется, когда уже имеется экземпляр `CompletableFuture`<br/>и нужно записать в него значение    |
| `public static <U> CompletableFuture<U>`<br/>`   completedFuture(U value)` | Создает объект `CompletableFuture`, содержащий уже вычисленное значение                               |
| `public boolean completeExceptionally(Throwable ex)` | Завершает объект `Future`, заисывая в него указанное исключение<br/>Ловится, как `ExecutionException` |

[Пример](examples/java/threads/completable_future/different_completions/ShipRepairYard.java)
```java
class Ship {
    private final String name;
    private int hull;

    Ship(String name) { this.name = name; }

    int getHull() { return hull; }

    void setHull(int hull) { this.hull = hull; }

    @Override
    public String toString() {
        return "Ship{name='" + name + "', hull=" + hull + '}';
    }
}
```
```java
class ShipRepairYard {
    private static final int REPAIRABLE_HULL_LIMIT = 15;
    private static final int REPAIR_HULL_NOT_NEED_LIMIT = 80;

    CompletableFuture<Ship> repairShip(Ship ship) {
        CompletableFuture<Ship> completableFuture = new CompletableFuture<>();
        if (ship.getHull() <= REPAIRABLE_HULL_LIMIT) {
            completableFuture = unRepairable(ship);
        } else if (ship.getHull() >= REPAIR_HULL_NOT_NEED_LIMIT) {
            completableFuture = noNeedToRepair(ship);
        } else {
            completableFuture = repair(ship);
        }
        return completableFuture;
    }

    /** Вставляем исключение в CompletableFuture. Потом ловится как ExecutionException */
    private CompletableFuture<Ship> unRepairable(Ship ship) {
        CompletableFuture<Ship> completableFuture = new CompletableFuture<>();
        completableFuture.completeExceptionally(
                new RuntimeException(ship + " не поддается починка", null));
        return completableFuture;
    }

    /** Создаем на основе уже выислинного значения */
    private CompletableFuture<Ship> noNeedToRepair(Ship ship) {
        System.out.println(ship + " не нуждается в ремонте на верфи");
        return CompletableFuture.completedFuture(ship);
    }

    /** Записываем в существующий CompletableFuture */
    private CompletableFuture<Ship> repair(Ship ship) {
        CompletableFuture<Ship> completableFuture = new CompletableFuture<>();
        System.out.println("Начало ремонта " + ship);
        try { TimeUnit.MILLISECONDS.sleep(100);
        } catch (InterruptedException e) { e.printStackTrace(); }
        ship.setHull(100);
        completableFuture.complete(ship);
        return completableFuture;
    }
}
```
```java
public class Fleet {
    private static ShipRepairYard repairYard = new ShipRepairYard();

    public static void main(String[] args) {
        sendRepairableShip();
        sendUnRepairableShip();
        sendShipWithNoNeedInRepair();
    }

    private static void sendAndWaitShip(Ship ship) {
        try {
            CompletableFuture<Ship> repairedShip = repairYard.repairShip(ship);
            System.out.println("С верфей вернулся " + repairedShip.get());
        } catch (InterruptedException | ExecutionException e) {
            System.out.println(e.getMessage());
        }
    }

    private static void sendRepairableShip() {
        Ship ship = new Ship("Стойкий");
        ship.setHull(50);
        sendAndWaitShip(ship);
    }

    private static void sendUnRepairableShip() {
        Ship ship = new Ship("Героический");
        ship.setHull(12);
        sendAndWaitShip(ship);
    }

    private static void sendShipWithNoNeedInRepair() {
        Ship ship = new Ship("Молненосный");
        ship.setHull(94);
        sendAndWaitShip(ship);
    }
}
```
_Коузен К. Современный Java: Рецепты программирования. Стр. 206-207_

## Отличие `get()` и `join()`
В методе `get()` объявлено проверяемое исключение `ExecutionException`<br/>
Метод `join()` отличается только тем, что при исключительном завершении возбуждает неконтролируемое исключение `CompletionException` (причиной которого также является оригинальное исключение
```java
public class CompletableFuture<T> implements Future<T>, CompletionStage<T> {
    ...
    public T get() throws InterruptedException, ExecutionException {...}
    ...
    /** ...
     * @throws CompletionException if this future completed
     * exceptionally or a completion computation threw an exception
     */
    public T join() {...}
    ...
}
```
И `get()`, и `join()` блокируют выполнение до тех пор, пока `Future` не завершиться или возбудет исключние<br/>
_Коузен К. Современный Java: Рецепты программирования. Стр. 208, 213_

## Отмена выполнения
Объект `CompletableFuture` можно отменить методом `cancel()`, принимающим параметр `boolean`<br/>
Если `Future` еще не завершен, , этот метод завершиться с исключением `CancellationException`<br/>
Аргументна данный момент игнорируется
```java
public class CancelLongOperation {
    public static void main(String[] args) {
        CompletableFuture<String> lineFromTooSlowSource = CompletableFuture.supplyAsync(() -> {
            try {
                TimeUnit.SECONDS.sleep(5);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            return "Long wawited line";
        });
        lineFromTooSlowSource.cancel(true);
        lineFromTooSlowSource.join();
    }
}
```
Вывод
```
Exception in thread "main" java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
	at ru.akhitev.kb.java6.multithreading.completable_future.CancelLongOperation.main(CancelLongOperation.java:16)
```
Чтобы увидеть исключение, нужно вызвать `join()` или `get()`. Именно в этот момент станет ясно, что операция отменена<br/>
_Коузен К. Современный Java: Рецепты программирования. Стр. 213_

## `runAsync(...)` и` supplyAsync(...)`, общий `ForkJoinPool` и `Executor`
Методы `runAsync(...)` полезны, если возвращать ничего не нужно<br/>
Методы `supplyAsync(...)` возвращают объект, получая его от заданного поставщика `Supplier`
```java
public class CompletableFuture<T> implements Future<T>, CompletionStage<T> {
    ...
    public static CompletableFuture<Void> runAsync(Runnable runnable) {...}
    public static CompletableFuture<Void> runAsync(Runnable runnable,
                                                   Executor executor) {...}
    ...
    public static <U> CompletableFuture<U> supplyAsync(Supplier<U> supplier) {...}
    public static <U> CompletableFuture<U> supplyAsync(Supplier<U> supplier,
                                                       Executor executor) {...}
    ...
}
```
В методах с одним аргументом используется общий пулл `ForkJoinPool`<br/>
В версии с двумя аргументами, можно передать свой `Executor`<br/>
[Пример](examples/java/threads/completable_future/async/ShipCaptain.java)
```java
public class ShipCaptain {

    public static void main(String[] args) {
        prepareAndSendStatusReport();
        CompletableFuture<String> replyToQuery = queryForInformation("Где последний раз был замечен противник в районе xyz?");
        System.out.println(replyToQuery.join());
    }

    static void prepareAndSendStatusReport() {
        CompletableFuture.runAsync(()-> {
            System.out.println("Начали отправку текущего статуса корабля");
            try {
                TimeUnit.MILLISECONDS.sleep(200);
            } catch (InterruptedException e) { e.printStackTrace(); }
            System.out.println("Отправка текущего статуса корабля окончена");
        });
    }

    static CompletableFuture<String> queryForInformation(String query) {
        return CompletableFuture.supplyAsync(()-> {
            System.out.println("Начали отправку запроса: " + query);
            try {
                TimeUnit.MILLISECONDS.sleep(200);
            } catch (InterruptedException e) { e.printStackTrace(); }
            System.out.println("По запросу [" + query + "] получен ответ");
            return "Ответ на запрос: " + query;
        });
    }
}
```
Вывод
```
Начали отправку текущего статуса корабля
Начали отправку запроса: Где последний раз был замечен противник в районе xyz?
Отправка текущего статуса корабля окончена
По запросу [Где последний раз был замечен противник в районе xyz?] получен ответ
Ответ на запрос: Где последний раз был замечен противник в районе xyz?
```
**Внимание:** если оставить в `main()` только `reportProvider.prepareAndSendStatusReport();`, ответа не будет!<br/>
Видимо, по аналогии с [ForkJoinPool.execute(...)](../18.9.%20Fork%20Join%20Framework/18.9.%20Fork%20Join%20Framework.md) асинхронные задачи являются демонами и завершаются, когда завершается вызывающий поток<br/>
_Коузен К. Современный Java: Рецепты программирования. Стр. 209_

## Связывание задач вместе через `thenRun()`, `thenApply()`, `thenAccept()`, `thenCompose()`, `thenCombine()`
Отличная особенность `CompletableFuture` состоит в том, что можно с его помощью связывать вместе объекты `Future`<br/>
Можно создать несколько объектов `Future`, а затем организовать их совместную работу так, что завершение одного станет сигналом для выполнения другого и так далее.
### `thenRun(...)`, когда нет ничего на входе и на выходе
[Пример](examples/java/threads/completable_future/coordination/PreparingBookSynopsis.java)
```java
public class PreparingBookSynopsis {
    public static void main(String[] args) {
        CompletableFuture
                .runAsync(() -> System.out.println("Прочитать с заметками главу про коллекции"))
                .thenRun(() -> System.out.println("Законспектировать по заметками главу про коллекции"))
                .thenRun(() -> System.out.println("Прочитать с заметками главу про IO"))
                .thenRun(() -> System.out.println("Законспектировать по заметками главу про IO"))
                .thenRun(() -> System.out.println("Прочитать с заметками главу про многопоточность"))
                .thenRun(() -> System.out.println("Законспектировать по заметками главу про многопоточность"));
    }
}
```
Вывод
```
Прочитать с заметками главу про коллекции
Законспектировать по заметками главу про коллекции
Прочитать с заметками главу про IO
Законспектировать по заметками главу про IO
Прочитать с заметками главу про многопоточность
Законспектировать по заметками главу про многопоточность
```
### `thenApply(...)`, когда ожидается какой то возврат
[Пример](examples/java/threads/completable_future/coordination/PreparingScienceArticle.java)
```java
public class PreparingScienceArticle {
    public static void main(String[] args) {
        Article printedArticle = CompletableFuture
                .supplyAsync(() -> {
                    Article article = new Article();
                    article.theme = "Важная проблема";
                    System.out.println("Оговорена тема с научным руководителем");
                    return article;
                })
                .thenApply((article) -> {
                    article.magazine = "Журнал ПИ";
                    System.out.println("Найден подходящий журнал");
                    return article;
                })
                .thenApply((article) -> {
                    article.text = "Много умных идей";
                    System.out.println("Статья написана");
                    return article;
                })
                .thenApply((article) -> {
                    article.recommendations = "Поправить тут и там";
                    System.out.println("Научный руководитель составил рекоммендации");
                    return article;
                })
                .thenApply((article) -> {
                    article.text = "Правильно изложенный умные мысли";
                    System.out.println("Проблемы в статье устранены");
                    return article;
                })
                .thenApply((article) -> {
                    System.out.println("Статья отправлена в печать");
                    return article;
                })
                .join();
        System.out.println(printedArticle);
    }

    private static class Article {
        private String theme;
        private String magazine;
        private String text;
        private String recommendations;

        @Override
        public String toString() {
            return "Article{" +
                    "theme='" + theme + '\'' +
                    ", magazine='" + magazine + '\'' +
                    ", text='" + text + '\'' +
                    ", recommendations='" + recommendations + '\'' +
                    '}';
        }
    }
}
```
Вывод
```
Оговорена тема с научным руководителем
Найден подходящий журнал
Статья написана
Научный руководитель составил рекоммендации
Проблемы в статье устранены
Статья отправлена в печать
Article{ theme='Важная проблема', magazine='Журнал ПИ', text='Правильно изложенный умные мысли', recommendations='Поправить тут и там'}
```
### `theAccept(...)`, когда есть что то на входе, но нет на выходе
[Пример](examples/java/threads/completable_future/coordination/WorkWithProblemTicket.java)
```java
public class WorkWithProblemTicket {
    public static void main(String[] args) {
        CompletableFuture
                .supplyAsync(() -> {
                    System.out.println("Тут, видимо, неправильное значение приходит из Perl");
                    System.out.println("Проконсультируюсь с Perl-разработчиокм");
                    return "Подскажи, где тут может быть проблема?";
                })
                .thenApply((question) -> {
                    System.out.println("Нашел проблему на вопрос: " + question);
                    return "Проблему тут";
                })
                .thenAccept((replyFromPerlEngineer) -> {
                    System.out.println("Пишу в тикет, что мы уже занимаемся решением проблемы");
                    System.out.println("Добавляю комментарий от Perl-разработчика: " + replyFromPerlEngineer);
                }).join();
    }
}
```
Вывод
```
Тут, видимо, неправильное значение приходит из Perl
Проконсультируюсь с Perl-разработчиокм
Нашел проблему на вопрос: Подскажи, где тут может быть проблема?
Пишу в тикет, что мы уже занимаемся решением проблемы
Добавляю комментарий от Perl-разработчика: Проблему тут
```
Если в конце не поставить `join()`, то в выводе ничего не будет или он будет не полным, так как основной поток завершиться и потоки `ForkJoinPool` закроются сразу после этого.<br/>
### `thenCompose()`
Альтернативой для `thenApply()` в объединении нескольких `CompletableFuture` является `thenCompose()`.<br/>
`thenApply()` можно представить аналогом `Optional.map()`, который возвращает новый `CompletionStage`, которое выполняется с результатом этого этапа.<br/>
`thenCompose()` можно представть, как `Optional.flatMap()`, который возвращает новый `CompletionStage` которое выполняется на этом этапе в качестве аргумента для функции.<br/>
Аргументом для `thenCompose()` является функция, которая принимает результат первого объекта `Future` и преобразует его в выход для второго.<br/>
[Пример](examples/java/threads/completable_future/coordination/compose/InboxRule.java)
```java
class Email {
    private final String from;
    private boolean autoRead;

    Email(String from) { this.from = from; }

    String getFrom() { return from; }
    boolean isAutoRead() { return autoRead; }
    boolean isEmailForRead() { return !autoRead; }
    void setAutoRead(boolean autoRead) { this.autoRead = autoRead; }

    @Override
    public String toString() {
        return "Email{ from='" + from + '\'' +
                ", autoRead=" + autoRead + '}';
    }
}
```
```java
public class InboxRule {
    private static String[] almostSpamList = new String[]{"donotreply@usefyl.com", "info@notbad.org"};
    public static void main(String[] args) {
        CompletableFuture<List<Email>> emailsAfterRules = CompletableFuture
                .supplyAsync(InboxRule::readInbox)
                .thenCompose(inbox ->
                        CompletableFuture.supplyAsync(() ->
                                inbox.stream().peek(email -> {
                                    for (String almostSpam : almostSpamList) {
                                        if (email.getFrom().equals(almostSpam)) {
                                            email.setAutoRead(true);
                                        }
                                    }
                                }).filter(Email::isEmailForRead).collect(Collectors.toList())));
        System.out.println(emailsAfterRules.join());
    }

    private static List<Email> readInbox() {
        List<Email> inbox = new ArrayList<>();
        Collections.addAll(inbox,
                new Email("donotreply@usefyl.com"),
                new Email("donotreply@customer.com"),
                new Email("info@notbad.org"),
                new Email("info@work.ru"),
                new Email("chief@work.ru"));
        return inbox;
    }
}
```
Вывод
```
[Email{ from='donotreply@customer.com', autoRead=false}, Email{ from='info@work.ru', autoRead=false}, Email{ from='chief@work.ru', autoRead=false}]
```
### `thenCombine()`
Если нужно по завершению двух задачи выполнить треью, то нужно использовать `thenCombine()`<br/>
Метод `thenCombine()` принимает `Future` и `BiFunction`, причем результаты обоих `Future` доступны в функции, выислящей результат.<br/>
[Пример](examples/java/threads/completable_future/coordination/CombineOfSaving.java)
```java
public class CombineOfSaving {
    public static void main(String[] args) {
        CompletableFuture<Boolean> save = CompletableFuture
                .supplyAsync(CombineOfSaving::saveToDb)
                .thenCombine(CompletableFuture.supplyAsync(CombineOfSaving::saveToBackUpQueue),
                        (saveToDb, saveToQueue) -> saveToDb && saveToQueue);
        System.out.println("Сохранение объектов в базу данных и резервную очередь прошло успешно? : "
                + save.join());
    }

    private static boolean saveToDb() {
        try {
            System.out.println("Начали сохранение в БД");
            TimeUnit.MILLISECONDS.sleep(200);
            System.out.println("Сохранение в БД успешно завершено");
            return true;
        } catch (InterruptedException e) {
            e.printStackTrace();
            return false;
        }
    }

    private static boolean saveToBackUpQueue() {
        try {
            System.out.println("Начали сохранение в резервную очередь");
            TimeUnit.MILLISECONDS.sleep(50);
            System.out.println("Сохранение в резервную очередь успешно завершено");
            return true;
        } catch (InterruptedException e) {
            e.printStackTrace();
            return false;
        }
    }
}
```
Вывод
```
Начали сохранение в БД
Начали сохранение в резервную очередь
Сохранение в резервную очередь успешно завершено
Сохранение в БД успешно завершено
Сохранение объектов в базу данных и резервную очередь прошло успешно? : true
```
### `thenRunAsync()`, `thenAcceptAsync()`, `thenApplyAsync()`, `thenCombineAsync()`, `thenComposeAsync()`
`thenAccept()`, `thenApply()` и другие выполняются  том же потоке, что и `supplyAsync()`.<br/>
Если вызвать `thenApplyAsync()` (или любой из перечисленных), то его задача будет передана в пулл и будет запущена в отдельном потоке<br/>
_Коузен К. Современный Java: Рецепты программирования. Стр. 210-212_<br/>
_[Vertex Academy: Java 8 CompletableFuture. Часть 1](https://vertex-academy.com/tutorials/ru/java-8-completablefuture/)_<br/>
_[Vertex Academy: Java 8 CompletableFuture. Часть 2](https://vertex-academy.com/tutorials/ru/java-8-completablefuture-part-2/)_

## Координация нескольких `CompletableFuture`
Для ожидания завершения нескольких или всех задач можно использовать методы:
* `allOf()`
* `anyOf()`

К слову, так можно заменить `CountDownLatch` [в примере](../18.6.%20Компоненты%20java.util.concurrent.library/examples/java/threads/concurrent/count_down_latch/Raid.java)<br/>
[Пример](examples/java/threads/completable_future/coordination/RaidToBoss.java)
```java
class RaidToBoss {
    public static void main(String[] args) {
        CompletableFuture agro = CompletableFuture.runAsync(RaidToBoss::agro);
        CompletableFuture buff = CompletableFuture.runAsync(RaidToBoss::buff);
        CompletableFuture deBuff = CompletableFuture.runAsync(RaidToBoss::deBuff);
        CompletableFuture.allOf(agro, buff, deBuff);
        CompletableFuture<Boolean> isBossDefeated = CompletableFuture.runAsync(RaidToBoss::attack)
                .thenApply((attackResult) -> defeatBoss());
        System.out.println("Босс повержен " + isBossDefeated.join());
    }

    private static void agro() {
        System.out.println("Такни начали агрить");
        try { TimeUnit.MILLISECONDS.sleep(50);
        } catch (InterruptedException e) { e.printStackTrace(); }
        System.out.println("Все сидят на танках");
    }

    private static void buff() {
        System.out.println("Рыцари, менсы и прочие начали бафать");
        try { TimeUnit.MILLISECONDS.sleep(100);
        } catch (InterruptedException e) { e.printStackTrace(); }
        System.out.println("Рейд пробаффан");
    }

    private static void deBuff() {
        System.out.println("ХМы, бурги и прочие начали дебафать");
        try { TimeUnit.MILLISECONDS.sleep(100);
        } catch (InterruptedException e) { e.printStackTrace(); }
        System.out.println("Противники отдебаффаны");
    }

    private static void attack() { System.out.println("Рейд пошел в атаку"); }

    private static boolean defeatBoss() { return true; }
}
```
Вывод
```
Такни начали агрить
Рыцари, менсы и прочие начали бафать
ХМы, бурги и прочие начали дебафать
Рейд пошел в атаку
Босс повержен true
```
_Коузен К. Современный Java: Рецепты программирования. Стр. 211, 220_

## Обработка исключений
```java
CompletableFuture<Integer> future = CompletableFuture
        .supplyAsync(() -> {
            throw new RuntimeException("error in async running");
        }).handle((obj, err) -> {
            System.out.print(err.getMessage());
            return 10;
        });
```
_[Vertex Academy: Java 8 CompletableFuture. Часть 2](https://vertex-academy.com/tutorials/ru/java-8-completablefuture-part-2/)_